version: '3'  #Se realiza la definicion de la sintaxis de docker compose que se utiliza

services:     # Sección que define los servicios de contenedores Docker

  grafana:    # Inicio de la defincion del servicio grafana

    image: grafana/grafana #La Imagen Docker utilizada para grafana

    ports: 

      - "3000:3000"  #Mapeo de puertos: 3000 del contenedor al 3000 de la maquina host

    volumes:

      - grafana_data:/var/lib/grafana #Volumes para la persistencia de datos de grafana

    depends_on:

      - mysql #Dependencia del servicio MySQL

    environment: #COnfiguración de las variables de enteorno del contenedor Grafana, coinfiguracion de conexion entre grafana y la BD.

      - GF_DATABASE_TYPE=mysql  #tipo de base de datos (MYSQL)
      - GF_DATABASE_HOST=mysql:3306 #Host y puerto de la base de datos MySQL
      - GF_DATABASE_NAME=newYorkMets #Nombre de la base de datos
      - GF_DATABASE_USER=root # Usuario de la base de datos
      - GF_DATABASE_PASSWORD=my-secret-pw #Contraseña de la base de datos

  mysql: # Inicio de la definición del servicio MySQL

    image: mysql:5.7 # Imagen Docker utilizada pars MySQL version 5.7

    volumes:

      - mysql_data:/var/lib/mysql # Volumen para persistencia de la base de datos MySQL

    environment: #Configuración de variuables de entorno del contenedor MySQL

      - MYSQL_ROOT_PASSWORD=my-secret-pw #Contraseña de root para Mysql
      - MYSQL_DATABASE=newYorkMets #nombre de la base de datos MySql

  redis: #Inicio de la definicion del servicio de redis
    image: redis:latest # Imagen Docker utilizada para Redis ultima version
    ports:
      - "6379:6379" #Mapeo de puertos: 6379 del contenedor al 6379 de la maquina host

volumes: # Se definen los volumenes para persistir datos de los servicios

  grafana_data:  # Volumen de datos de grafana

  mysql_data:  # Volumen de datos de MySql 

  #se sube a git
  
